"""user_categpry added

Revision ID: 9287f7e4b8ca
Revises: fc92105b395d
Create Date: 2025-05-04 14:13:00.706114

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9287f7e4b8ca'
down_revision: Union[str, None] = 'fc92105b395d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.drop_constraint('category_user_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('category_user_id_fkey', 'category', 'users', ['user_id'], ['id'])
    op.drop_table('user_category_link')
    # ### end Alembic commands ###
